language: python
python:
 - "2.6"
 - "2.7"
 - "pypy"

before_install:
# Workaround for a permissions issue with Travis virtual machine images
# that breaks Python's multiprocessing:
# https://github.com/travis-ci/travis-cookbooks/issues/155
 - sudo rm -rf /dev/shm
 - sudo ln -s /run/shm /dev/shm

script:
 - "PYTHONPATH=./ python test/test_pyNGSQC.py"
